import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Nav
    home: 'Home', symptomCheck: 'Symptom Check', pcod: 'PCOD', neuroCheck: 'Neuro Check',
    appointments: 'Appointments', emergency: 'Emergency', records: 'Records', about: 'About', login: 'Login',
    // Common
    bookDoctor: 'Book a Doctor', saveRecords: 'Save to Records', startOver: 'Start Over',
    riskLow: 'Low Risk', riskModerate: 'Moderate Risk', riskHigh: 'High Risk',
    disclaimer: 'This is NOT a medical diagnosis. Always consult a doctor.',
    next: 'Next', back: 'Back', getResults: 'Get My Results',
    yes: 'Yes', no: 'No', dontKnow: "Don't know", retake: 'Retake',
    // Symptom checker
    basicInfo: 'Basic Information', age: 'Age', gender: 'Gender', weight: 'Weight (kg)',
    whatSymptoms: 'What symptoms do you have?', lifestyle: 'Lifestyle Information',
    yourAnalysis: 'Your Symptom Analysis', possibleConditions: 'Possible conditions',
    recommendation: 'Recommendation', savedToRecords: 'Saved to Records ✓',
    // PCOD
    pcodTitle: 'PCOD / PCOS Risk Checker',
    pcodSubtitle: 'Answer these questions honestly to get a personalised early risk estimate for PCOD/PCOS.',
    yourInfo: 'Your Information', fullName: 'Full Name', emailOptional: 'Email (optional)',
    cyclePattern: 'Menstrual Cycle Pattern', weightBmi: 'Weight / BMI Category',
    familyHistory: 'Family History of PCOD/PCOS?', symptomsExperience: 'Symptoms You Experience',
    selectAllApply: 'Select all that apply to you.', checkMyRisk: 'Check My Risk',
    yourPCODResult: 'Your PCOD Risk Assessment', score: 'Score',
    saveToRecords: 'Save to Records', bookGynecologist: 'Book Gynecologist',
    // Neuro
    neuroTitle: 'Neuro / Stroke Risk Check',
    neuroSubtitle: 'Identify early warning signs of stroke and neurological emergencies in minutes.',
    neuroUrgent: 'If you are currently experiencing stroke symptoms — call 112 immediately.',
    medicalHistory: 'Medical History', lifestyleHabits: 'Lifestyle Habits',
    currentSymptoms: 'Current or Recent Symptoms', checkNeuroRisk: 'Check My Neuro Risk',
    bloodPressure: 'Blood pressure history', diabetes: 'Diabetes history',
    cholesterol: 'Cholesterol levels', smoking: 'Smoking', alcohol: 'Alcohol',
    yourNeuroResult: 'Your Neuro Risk Assessment', callNow: 'Call 112 Now',
    bookNeurologist: 'Book Neurologist', findHospital: 'Find Nearest Hospital',
    // Records
    myHealthRecords: 'My Health Records', healthTrends: 'Health Trends',
    analyticsSubtitle: 'Track your risk scores, weight, and vitals over time.',
    assessmentHistory: 'Assessment History', uploadedDocs: 'Uploaded Documents',
    reminders: 'Health Reminders', diagnosisReport: 'AI Diagnosis Report',
    weightKg: 'Weight (kg)', bpSystolic: 'BP Systolic (mmHg)', riskScore: 'Risk Score',
    enableReminders: 'Enable WhatsApp Reminders', reminderSaved: 'Reminders saved! You will receive WhatsApp alerts.',
    phone: 'WhatsApp Phone Number', frequency: 'Reminder Frequency',
    daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly',
    consultFollowup: 'Follow-up Consultation', medicationAlert: 'Medication Alert', bpCheck: 'BP Check Reminder',
    viewDetails: 'View Details', hide: 'Hide', encryptedPrivate: 'Encrypted & Private',
    uploadHint: 'Click to upload or drag and drop', noDocuments: 'No documents uploaded yet.',
    diagnosisTitle: 'AI-Assisted Diagnosis Summary', diagnosisNote: 'Based on your assessment history:',
    possibleCond: 'Possible Conditions', recommendations: 'Recommendations', urgency: 'Urgency Level',
    // Emergency
    emergencySupport: 'Emergency Support', nearbyHospitals: 'Nearby Hospitals',
    detectNearest: 'Detect Nearest', shareLocation: 'Share Location', shared: 'Shared',
    whileWaiting: 'While Waiting for Help', callAmbulance: 'Call Ambulance',
    // Appointments
    bookAppointment: 'Book a Doctor', searchPlaceholder: 'Search by name or specialty...',
    // About
    ourMission: 'Our Mission', problemsWeSolve: 'Problems We Solve', ourSolution: 'Our Solution',
    teamLead: 'Team Lead',
    // Home hero
    heroTagline: 'Trusted by thousands of patients across India',
    heroTitle: 'Early Health Risk Detection for PCOD, Stroke & Cardiac',
    heroSub: 'AI-powered platform for early disease detection and smarter healthcare access — designed for women, rural communities, and everyone who deserves timely care.',
    startSymptomCheck: 'Start Symptom Check', checkPCODRisk: 'Check PCOD Risk', emergencyHelpNow: 'Emergency Help Now',
    usersHelped: 'Users Helped', support247: 'Support',
    // Home page extras
    symptomCheckDesc: 'Multi-step assessment of your symptoms with risk indicators and specialist recommendations.',
    pcodDesc: 'Dedicated screening for PCOD/PCOS using cycle patterns, symptoms, and lifestyle data.',
    neuroCheckDesc: 'Identify early warning signs of stroke and neurological emergencies before they escalate.',
    womensHealth: "Women's Health", urgent: 'Urgent',
    aiPoweredTools: 'AI-Powered Tools', checkRiskNow: 'Check Your Risk Now', startCheck: 'Start Check',
    theProblem: 'The Problem', whatWereSolving: "What We're Solving",
    howWeHelp: 'How We Help',
    prob1: 'Early symptoms of PCOD/PCOS are often missed or dismissed by patients and doctors alike',
    prob2: 'Warning signs of stroke and cardiac emergencies frequently go unrecognised until too late',
    prob3: 'Rural and low-income communities lack easy access to specialist healthcare',
    prob4: 'No single platform combining prediction, doctor access, and emergency support',
    prob5: 'Medical language excludes patients with low health literacy',
    sol1: 'AI-assisted symptom screening with plain-language results',
    sol2: 'PCOD / PCOS risk detection with personalised recommendations',
    sol3: 'Neuro / Stroke early warning with urgent red alerts',
    sol4: 'Book specialists online or in-person in minutes',
    sol5: 'One-tap emergency support with location-based contacts',
    sol6: 'Digital health records to track risk over time',
    ctaTitle: 'Ready to check your health risk?', ctaSub: 'Takes 2–3 minutes. Free.',
    startFreeCheck: 'Start Free Check',
    impactSdgs: 'Impact & SDGs', alignedGoals: 'Aligned with UN Development Goals',
    sdg3: 'Good Health & Well-Being', sdg9: 'Industry, Innovation & Infrastructure', sdg10: 'Reduced Inequalities',
    learnMore: 'Learn more about our impact & team',
  },
  hi: {
    home: 'होम', symptomCheck: 'लक्षण जांच', pcod: 'पीसीओडी', neuroCheck: 'न्यूरो जांच',
    appointments: 'अपॉइंटमेंट', emergency: 'आपातकाल', records: 'रिकॉर्ड', about: 'हमारे बारे में', login: 'लॉगिन',
    bookDoctor: 'डॉक्टर बुक करें', saveRecords: 'रिकॉर्ड में सहेजें', startOver: 'फिर से शुरू करें',
    riskLow: 'कम जोखिम', riskModerate: 'मध्यम जोखिम', riskHigh: 'उच्च जोखिम',
    disclaimer: 'यह चिकित्सीय निदान नहीं है। हमेशा डॉक्टर से परामर्श लें।',
    next: 'अगला', back: 'वापस', getResults: 'परिणाम देखें',
    yes: 'हाँ', no: 'नहीं', dontKnow: 'नहीं जानता', retake: 'दोबारा करें',
    basicInfo: 'बुनियादी जानकारी', age: 'आयु', gender: 'लिंग', weight: 'वजन (किग्रा)',
    whatSymptoms: 'आपके क्या लक्षण हैं?', lifestyle: 'जीवनशैली की जानकारी',
    yourAnalysis: 'आपका लक्षण विश्लेषण', possibleConditions: 'संभावित स्थितियां',
    recommendation: 'सुझाव', savedToRecords: 'रिकॉर्ड में सहेजा ✓',
    pcodTitle: 'पीसीओडी / पीसीओएस जोखिम परीक्षक',
    pcodSubtitle: 'पीसीओडी/पीसीओएस के लिए प्रारंभिक जोखिम अनुमान प्राप्त करें।',
    yourInfo: 'आपकी जानकारी', fullName: 'पूरा नाम', emailOptional: 'ईमेल (वैकल्पिक)',
    cyclePattern: 'मासिक धर्म चक्र', weightBmi: 'वजन / बीएमआई श्रेणी',
    familyHistory: 'पीसीओडी का पारिवारिक इतिहास?', symptomsExperience: 'आपके लक्षण',
    selectAllApply: 'सभी लागू विकल्प चुनें।', checkMyRisk: 'जोखिम जांचें',
    yourPCODResult: 'आपका पीसीओडी जोखिम मूल्यांकन', score: 'स्कोर',
    saveToRecords: 'रिकॉर्ड में सहेजें', bookGynecologist: 'स्त्री रोग विशेषज्ञ बुक करें',
    neuroTitle: 'न्यूरो / स्ट्रोक जोखिम जांच',
    neuroSubtitle: 'स्ट्रोक के प्रारंभिक चेतावनी संकेतों की पहचान करें।',
    neuroUrgent: 'यदि आप अभी स्ट्रोक के लक्षण अनुभव कर रहे हैं — तुरंत 112 पर कॉल करें।',
    medicalHistory: 'चिकित्सा इतिहास', lifestyleHabits: 'जीवनशैली की आदतें',
    currentSymptoms: 'वर्तमान या हालिया लक्षण', checkNeuroRisk: 'न्यूरो जोखिम जांचें',
    bloodPressure: 'रक्तचाप इतिहास', diabetes: 'मधुमेह इतिहास',
    cholesterol: 'कोलेस्ट्रॉल स्तर', smoking: 'धूम्रपान', alcohol: 'शराब',
    yourNeuroResult: 'आपका न्यूरो जोखिम मूल्यांकन', callNow: 'अभी 112 पर कॉल करें',
    bookNeurologist: 'न्यूरोलॉजिस्ट बुक करें', findHospital: 'नजदीकी अस्पताल खोजें',
    myHealthRecords: 'मेरे स्वास्थ्य रिकॉर्ड', healthTrends: 'स्वास्थ्य रुझान',
    analyticsSubtitle: 'समय के साथ अपने जोखिम स्कोर और वजन को ट्रैक करें।',
    assessmentHistory: 'मूल्यांकन इतिहास', uploadedDocs: 'अपलोड किए दस्तावेज़',
    reminders: 'स्वास्थ्य अनुस्मारक', diagnosisReport: 'AI निदान रिपोर्ट',
    weightKg: 'वजन (किग्रा)', bpSystolic: 'रक्तचाप (mmHg)', riskScore: 'जोखिम स्कोर',
    enableReminders: 'WhatsApp अनुस्मारक चालू करें', reminderSaved: 'अनुस्मारक सहेजे गए!',
    phone: 'WhatsApp नंबर', frequency: 'आवृत्ति',
    daily: 'दैनिक', weekly: 'साप्ताहिक', monthly: 'मासिक',
    consultFollowup: 'अनुवर्ती परामर्श', medicationAlert: 'दवा अलर्ट', bpCheck: 'रक्तचाप जांच',
    viewDetails: 'विवरण देखें', hide: 'छुपाएं', encryptedPrivate: 'एन्क्रिप्टेड और निजी',
    uploadHint: 'अपलोड करने के लिए क्लिक करें', noDocuments: 'कोई दस्तावेज़ अपलोड नहीं।',
    diagnosisTitle: 'AI निदान सारांश', diagnosisNote: 'आपके मूल्यांकन के आधार पर:',
    possibleCond: 'संभावित स्थितियां', recommendations: 'सुझाव', urgency: 'तात्कालिकता',
    emergencySupport: 'आपातकालीन सहायता', nearbyHospitals: 'नजदीकी अस्पताल',
    detectNearest: 'नजदीकी खोजें', shareLocation: 'स्थान साझा करें', shared: 'साझा किया',
    whileWaiting: 'सहायता की प्रतीक्षा में', callAmbulance: 'एम्बुलेंस बुलाएं',
    bookAppointment: 'डॉक्टर बुक करें', searchPlaceholder: 'नाम या विशेषता खोजें...',
    ourMission: 'हमारा मिशन', problemsWeSolve: 'हम क्या समस्याएं हल करते हैं', ourSolution: 'हमारा समाधान',
    teamLead: 'टीम लीड',
    heroTagline: 'भारत भर के हजारों मरीजों का विश्वास',
    heroTitle: 'पीसीओडी, स्ट्रोक और हृदय रोग का शीघ्र पता लगाएं',
    heroSub: 'AI-संचालित स्वास्थ्य प्लेटफ़ॉर्म — सभी के लिए स्मार्ट स्वास्थ्य सेवा।',
    startSymptomCheck: 'लक्षण जांच शुरू करें', checkPCODRisk: 'पीसीओडी जोखिम जांचें', emergencyHelpNow: 'आपातकालीन सहायता',
    usersHelped: 'उपयोगकर्ता', support247: 'सहायता',
    symptomCheckDesc: 'आपके लक्षणों का बहु-चरण मूल्यांकन और विशेषज्ञ सिफारिशें।',
    pcodDesc: 'पीसीओडी/पीसीओएस के लिए समर्पित जांच।',
    neuroCheckDesc: 'स्ट्रोक के शुरुआती चेतावनी संकेतों की पहचान करें।',
    womensHealth: 'महिला स्वास्थ्य', urgent: 'तत्काल',
    aiPoweredTools: 'AI-संचालित उपकरण', checkRiskNow: 'अभी जोखिम जांचें', startCheck: 'जांच शुरू करें',
    theProblem: 'समस्या', whatWereSolving: 'हम क्या हल कर रहे हैं',
    howWeHelp: 'हम कैसे मदद करते हैं',
    prob1: 'पीसीओडी/पीसीओएस के शुरुआती लक्षण अक्सर नजरअंदाज किए जाते हैं',
    prob2: 'स्ट्रोक के चेतावनी संकेत अक्सर देर से पहचाने जाते हैं',
    prob3: 'ग्रामीण समुदायों को विशेषज्ञ स्वास्थ्य सेवा तक पहुंच नहीं',
    prob4: 'कोई एकल प्लेटफ़ॉर्म नहीं जो भविष्यवाणी, डॉक्टर और आपातकाल को जोड़े',
    prob5: 'चिकित्सा भाषा कम स्वास्थ्य साक्षरता वाले रोगियों को बाहर करती है',
    sol1: 'सरल भाषा में AI-सहायक लक्षण जांच',
    sol2: 'पीसीओडी/पीसीओएस जोखिम पहचान',
    sol3: 'न्यूरो/स्ट्रोक चेतावनी',
    sol4: 'मिनटों में विशेषज्ञ बुक करें',
    sol5: 'एक-टैप आपातकालीन सहायता',
    sol6: 'डिजिटल स्वास्थ्य रिकॉर्ड',
    ctaTitle: 'अपने स्वास्थ्य जोखिम की जांच के लिए तैयार हैं?', ctaSub: '2-3 मिनट लगते हैं। निःशुल्क।',
    startFreeCheck: 'निःशुल्क जांच शुरू करें',
    impactSdgs: 'प्रभाव और SDGs', alignedGoals: 'UN विकास लक्ष्यों के अनुरूप',
    sdg3: 'अच्छा स्वास्थ्य और कल्याण', sdg9: 'उद्योग, नवाचार और बुनियादी ढांचा', sdg10: 'असमानताओं में कमी',
    learnMore: 'हमारे प्रभाव और टीम के बारे में अधिक जानें',
  },
  ta: {
    home: 'முகப்பு', symptomCheck: 'அறிகுறி சோதனை', pcod: 'பிசிஓடி', neuroCheck: 'நரம்பு சோதனை',
    appointments: 'சந்திப்புகள்', emergency: 'அவசரநிலை', records: 'பதிவுகள்', about: 'பற்றி', login: 'உள்நுழை',
    bookDoctor: 'மருத்துவர் பதிவு', saveRecords: 'பதிவுகளில் சேமி', startOver: 'மீண்டும் தொடங்கு',
    riskLow: 'குறைந்த அபாயம்', riskModerate: 'மிதமான அபாயம்', riskHigh: 'அதிக அபாயம்',
    disclaimer: 'இது மருத்துவ நோயறிதல் அல்ல. மருத்துவரை அணுகவும்.',
    next: 'அடுத்து', back: 'பின்', getResults: 'முடிவுகளை பெறு',
    yes: 'ஆம்', no: 'இல்லை', dontKnow: 'தெரியாது', retake: 'மீண்டும் செய்',
    basicInfo: 'அடிப்படை தகவல்', age: 'வயது', gender: 'பாலினம்', weight: 'எடை (கிகி)',
    whatSymptoms: 'உங்கள் அறிகுறிகள் என்ன?', lifestyle: 'வாழ்க்கை முறை தகவல்',
    yourAnalysis: 'உங்கள் அறிகுறி பகுப்பாய்வு', possibleConditions: 'சாத்தியமான நிலைமைகள்',
    recommendation: 'பரிந்துரை', savedToRecords: 'பதிவுகளில் சேமிக்கப்பட்டது ✓',
    pcodTitle: 'பிசிஓடி / பிசிஓஎஸ் அபாய சோதனை',
    pcodSubtitle: 'பிசிஓடி/பிசிஓஎஸ் ஆரம்ப அபாய மதிப்பீடு பெறுங்கள்.',
    yourInfo: 'உங்கள் தகவல்', fullName: 'முழு பெயர்', emailOptional: 'மின்னஞ்சல் (விருப்பம்)',
    cyclePattern: 'மாதவிடாய் சுழற்சி', weightBmi: 'எடை / பிஎம்ஐ வகை',
    familyHistory: 'பிசிஓடியின் குடும்ப வரலாறு?', symptomsExperience: 'நீங்கள் அனுபவிக்கும் அறிகுறிகள்',
    selectAllApply: 'பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்.', checkMyRisk: 'என் அபாயம் சரிபார்',
    yourPCODResult: 'உங்கள் பிசிஓடி அபாய மதிப்பீடு', score: 'மதிப்பெண்',
    saveToRecords: 'பதிவுகளில் சேமி', bookGynecologist: 'மகப்பேறு மருத்துவர் பதிவு',
    neuroTitle: 'நரம்பு / பக்கவாதம் அபாய சோதனை',
    neuroSubtitle: 'பக்கவாதத்தின் ஆரம்ப எச்சரிக்கை அறிகுறிகளை கண்டறியுங்கள்.',
    neuroUrgent: 'நீங்கள் இப்போது பக்கவாத அறிகுறிகளை அனுபவிக்கிறீர்களா — 112ஐ அழைக்கவும்.',
    medicalHistory: 'மருத்துவ வரலாறு', lifestyleHabits: 'வாழ்க்கை முறை பழக்கங்கள்',
    currentSymptoms: 'தற்போதைய அறிகுறிகள்', checkNeuroRisk: 'நரம்பு அபாயம் சரிபார்',
    bloodPressure: 'இரத்த அழுத்த வரலாறு', diabetes: 'நீரிழிவு வரலாறு',
    cholesterol: 'கொழுப்பு அளவு', smoking: 'புகைபிடித்தல்', alcohol: 'மது',
    yourNeuroResult: 'உங்கள் நரம்பு அபாய மதிப்பீடு', callNow: 'இப்போது 112 அழை',
    bookNeurologist: 'நரம்பியல் நிபுணர் பதிவு', findHospital: 'அருகிலுள்ள மருத்துவமனை',
    myHealthRecords: 'என் சுகாதார பதிவுகள்', healthTrends: 'சுகாதார போக்குகள்',
    analyticsSubtitle: 'காலப்போக்கில் உங்கள் ஆபத்து மதிப்பெண்களை கண்காணிக்கவும்.',
    assessmentHistory: 'மதிப்பீட்டு வரலாறு', uploadedDocs: 'பதிவேற்றப்பட்ட ஆவணங்கள்',
    reminders: 'சுகாதார நினைவூட்டல்கள்', diagnosisReport: 'AI நோயறிதல் அறிக்கை',
    weightKg: 'எடை (கிகி)', bpSystolic: 'இரத்த அழுத்தம் (mmHg)', riskScore: 'அபாய மதிப்பெண்',
    enableReminders: 'WhatsApp நினைவூட்டல்களை இயக்கு', reminderSaved: 'நினைவூட்டல்கள் சேமிக்கப்பட்டன!',
    phone: 'WhatsApp எண்', frequency: 'நினைவூட்டல் அதிர்வெண்',
    daily: 'தினசரி', weekly: 'வாராந்திர', monthly: 'மாதாந்திர',
    consultFollowup: 'தொடர் ஆலோசனை', medicationAlert: 'மருந்து எச்சரிக்கை', bpCheck: 'இரத்த அழுத்த சோதனை',
    viewDetails: 'விவரங்களை பார்', hide: 'மறை', encryptedPrivate: 'குறியாக்கப்பட்டது',
    uploadHint: 'பதிவேற்ற கிளிக் செய்யவும்', noDocuments: 'ஆவணங்கள் இல்லை.',
    diagnosisTitle: 'AI நோயறிதல் சுருக்கம்', diagnosisNote: 'உங்கள் மதிப்பீட்டின் அடிப்படையில்:',
    possibleCond: 'சாத்தியமான நிலைமைகள்', recommendations: 'பரிந்துரைகள்', urgency: 'அவசர நிலை',
    emergencySupport: 'அவசர ஆதரவு', nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகள்',
    detectNearest: 'அருகிலுள்ளதை கண்டறி', shareLocation: 'இருப்பிடம் பகிர்', shared: 'பகிரப்பட்டது',
    whileWaiting: 'உதவிக்காக காத்திருக்கும் போது', callAmbulance: 'ஆம்புலன்ஸ் அழை',
    bookAppointment: 'மருத்துவர் பதிவு', searchPlaceholder: 'பெயர் அல்லது சிறப்பு தேடு...',
    ourMission: 'எங்கள் நோக்கம்', problemsWeSolve: 'நாங்கள் தீர்க்கும் சிக்கல்கள்', ourSolution: 'எங்கள் தீர்வு',
    teamLead: 'குழு தலைவர்',
    heroTagline: 'இந்தியா முழுவதும் ஆயிரக்கணக்கான நோயாளிகளின் நம்பிக்கை',
    heroTitle: 'பிசிஓடி, பக்கவாதம் மற்றும் இதய நோய்களை முன்கூட்டியே கண்டறியுங்கள்',
    heroSub: 'AI சுகாதார தளம் — அனைவருக்கும் சிறந்த சுகாதார அணுகல்.',
    startSymptomCheck: 'அறிகுறி சோதனை தொடங்கு', checkPCODRisk: 'பிசிஓடி அபாயம் சரிபார்', emergencyHelpNow: 'அவசர உதவி',
    usersHelped: 'பயனர்கள்', support247: 'ஆதரவு',
    symptomCheckDesc: 'உங்கள் அறிகுறிகளின் பல-படி மதிப்பீடு மற்றும் நிபுணர் பரிந்துரைகள்.',
    pcodDesc: 'பிசிஓடி/பிசிஓஎஸ்க்கான சிறப்பு திரையிடல்.',
    neuroCheckDesc: 'பக்கவாதத்தின் ஆரம்ப எச்சரிக்கை அறிகுறிகளை கண்டறியுங்கள்.',
    womensHealth: 'பெண்கள் ஆரோக்கியம்', urgent: 'அவசரம்',
    aiPoweredTools: 'AI-இயக்கும் கருவிகள்', checkRiskNow: 'இப்போது அபாயம் சரிபார்', startCheck: 'சோதனை தொடங்கு',
    theProblem: 'சிக்கல்', whatWereSolving: 'நாங்கள் என்ன தீர்க்கிறோம்',
    howWeHelp: 'நாங்கள் எவ்வாறு உதவுகிறோம்',
    prob1: 'பிசிஓடி/பிசிஓஎஸ் ஆரம்ப அறிகுறிகள் அடிக்கடி கவனிக்கப்படுவதில்லை',
    prob2: 'பக்கவாத எச்சரிக்கை அறிகுறிகள் தாமதமாக கண்டறியப்படுகின்றன',
    prob3: 'கிராமப்புற சமூகங்களுக்கு நிபுணர் சுகாதார அணுகல் இல்லை',
    prob4: 'கணிப்பு, மருத்துவர்கள் மற்றும் அவசரநிலையை இணைக்கும் தளம் இல்லை',
    prob5: 'மருத்துவ மொழி குறைந்த சுகாதார படிப்பறிவுள்ளவர்களை விலக்குகிறது',
    sol1: 'எளிய மொழியில் AI-உதவி அறிகுறி சோதனை',
    sol2: 'பிசிஓடி/பிசிஓஎஸ் அபாய கண்டறிதல்',
    sol3: 'நரம்பு/பக்கவாத எச்சரிக்கை',
    sol4: 'நிமிடங்களில் நிபுணர்களை பதிவு செய்யுங்கள்',
    sol5: 'ஒரு-தட்டு அவசர ஆதரவு',
    sol6: 'டிஜிட்டல் சுகாதார பதிவுகள்',
    ctaTitle: 'உங்கள் சுகாதார அபாயத்தை சரிபார்க்க தயாரா?', ctaSub: '2-3 நிமிடங்கள் மட்டுமே. இலவசம்.',
    startFreeCheck: 'இலவச சோதனை தொடங்கு',
    impactSdgs: 'தாக்கம் மற்றும் SDGs', alignedGoals: 'UN வளர்ச்சி இலக்குகளுடன் இணைந்தது',
    sdg3: 'நல்ல சுகாதாரம் மற்றும் நலன்', sdg9: 'தொழில், புதுமை மற்றும் உள்கட்டமைப்பு', sdg10: 'சமத்துவமின்மை குறைப்பு',
    learnMore: 'எங்கள் தாக்கம் மற்றும் குழுவைப் பற்றி மேலும் அறியுங்கள்',
  },
  kn: {
    home: 'ಮನೆ', symptomCheck: 'ರೋಗಲಕ್ಷಣ ಪರೀಕ್ಷೆ', pcod: 'ಪಿಸಿಒಡಿ', neuroCheck: 'ನ್ಯೂರೋ ಪರೀಕ್ಷೆ',
    appointments: 'ಅಪಾಯಿಂಟ್ಮೆಂಟ್', emergency: 'ತುರ್ತು', records: 'ದಾಖಲೆಗಳು', about: 'ನಮ್ಮ ಬಗ್ಗೆ', login: 'ಲಾಗಿನ್',
    bookDoctor: 'ವೈದ್ಯರನ್ನು ಬುಕ್ ಮಾಡಿ', saveRecords: 'ದಾಖಲೆಗಳಲ್ಲಿ ಉಳಿಸಿ', startOver: 'ಮತ್ತೆ ಶುರು ಮಾಡಿ',
    riskLow: 'ಕಡಿಮೆ ಅಪಾಯ', riskModerate: 'ಮಧ್ಯಮ ಅಪಾಯ', riskHigh: 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    disclaimer: 'ಇದು ವೈದ್ಯಕೀಯ ರೋಗನಿರ್ಣಯ ಅಲ್ಲ. ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    next: 'ಮುಂದೆ', back: 'ಹಿಂದೆ', getResults: 'ಫಲಿತಾಂಶ ಪಡೆಯಿರಿ',
    yes: 'ಹೌದು', no: 'ಇಲ್ಲ', dontKnow: 'ತಿಳಿದಿಲ್ಲ', retake: 'ಮತ್ತೆ ತೆಗೆದುಕೊಳ್ಳಿ',
    basicInfo: 'ಮೂಲ ಮಾಹಿತಿ', age: 'ವಯಸ್ಸು', gender: 'ಲಿಂಗ', weight: 'ತೂಕ (ಕೆಜಿ)',
    whatSymptoms: 'ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳು ಯಾವುವು?', lifestyle: 'ಜೀವನಶೈಲಿ ಮಾಹಿತಿ',
    yourAnalysis: 'ನಿಮ್ಮ ರೋಗಲಕ್ಷಣ ವಿಶ್ಲೇಷಣೆ', possibleConditions: 'ಸಂಭವನೀಯ ಸ್ಥಿತಿಗಳು',
    recommendation: 'ಶಿಫಾರಸು', savedToRecords: 'ದಾಖಲೆಗಳಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ ✓',
    pcodTitle: 'ಪಿಸಿಒಡಿ / ಪಿಸಿಒಎಸ್ ಅಪಾಯ ಪರೀಕ್ಷೆ',
    pcodSubtitle: 'ಪಿಸಿಒಡಿ/ಪಿಸಿಒಎಸ್‌ಗಾಗಿ ಆರಂಭಿಕ ಅಪಾಯ ಅಂದಾಜು ಪಡೆಯಿರಿ.',
    yourInfo: 'ನಿಮ್ಮ ಮಾಹಿತಿ', fullName: 'ಪೂರ್ಣ ಹೆಸರು', emailOptional: 'ಇಮೇಲ್ (ಐಚ್ಛಿಕ)',
    cyclePattern: 'ಮುಟ್ಟಿನ ಚಕ್ರ', weightBmi: 'ತೂಕ / ಬಿಎಂಐ ವರ್ಗ',
    familyHistory: 'ಪಿಸಿಒಡಿಯ ಕುಟುಂಬ ಇತಿಹಾಸ?', symptomsExperience: 'ನೀವು ಅನುಭವಿಸುವ ರೋಗಲಕ್ಷಣಗಳು',
    selectAllApply: 'ಅನ್ವಯಿಸುವ ಎಲ್ಲವನ್ನೂ ಆರಿಸಿ.', checkMyRisk: 'ನನ್ನ ಅಪಾಯ ಪರಿಶೀಲಿಸಿ',
    yourPCODResult: 'ನಿಮ್ಮ ಪಿಸಿಒಡಿ ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ', score: 'ಸ್ಕೋರ್',
    saveToRecords: 'ದಾಖಲೆಗಳಲ್ಲಿ ಉಳಿಸಿ', bookGynecologist: 'ಸ್ತ್ರೀರೋಗ ತಜ್ಞರನ್ನು ಬುಕ್ ಮಾಡಿ',
    neuroTitle: 'ನ್ಯೂರೋ / ಸ್ಟ್ರೋಕ್ ಅಪಾಯ ಪರೀಕ್ಷೆ',
    neuroSubtitle: 'ಸ್ಟ್ರೋಕ್‌ನ ಆರಂಭಿಕ ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳನ್ನು ಗುರುತಿಸಿ.',
    neuroUrgent: 'ನೀವು ಈಗ ಸ್ಟ್ರೋಕ್ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಅನುಭವಿಸುತ್ತಿದ್ದರೆ — ತಕ್ಷಣ 112 ಕರೆ ಮಾಡಿ.',
    medicalHistory: 'ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ', lifestyleHabits: 'ಜೀವನಶೈಲಿ ಅಭ್ಯಾಸಗಳು',
    currentSymptoms: 'ಪ್ರಸ್ತುತ ರೋಗಲಕ್ಷಣಗಳು', checkNeuroRisk: 'ನ್ಯೂರೋ ಅಪಾಯ ಪರಿಶೀಲಿಸಿ',
    bloodPressure: 'ರಕ್ತದೊತ್ತಡ ಇತಿಹಾಸ', diabetes: 'ಮಧುಮೇಹ ಇತಿಹಾಸ',
    cholesterol: 'ಕೊಲೆಸ್ಟ್ರಾಲ್ ಮಟ್ಟ', smoking: 'ಧೂಮಪಾನ', alcohol: 'ಮದ್ಯ',
    yourNeuroResult: 'ನಿಮ್ಮ ನ್ಯೂರೋ ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ', callNow: 'ಈಗ 112 ಕರೆ ಮಾಡಿ',
    bookNeurologist: 'ನರವಿಜ್ಞಾನಿ ಬುಕ್ ಮಾಡಿ', findHospital: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ',
    myHealthRecords: 'ನನ್ನ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು', healthTrends: 'ಆರೋಗ್ಯ ಟ್ರೆಂಡ್ಸ್',
    analyticsSubtitle: 'ಕಾಲಾನಂತರದಲ್ಲಿ ನಿಮ್ಮ ಅಪಾಯ ಸ್ಕೋರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    assessmentHistory: 'ಮೌಲ್ಯಮಾಪನ ಇತಿಹಾಸ', uploadedDocs: 'ಅಪ್ಲೋಡ್ ಮಾಡಿದ ದಾಖಲೆಗಳು',
    reminders: 'ಆರೋಗ್ಯ ಜ್ಞಾಪಕಗಳು', diagnosisReport: 'AI ರೋಗನಿರ್ಣಯ ವರದಿ',
    weightKg: 'ತೂಕ (ಕೆಜಿ)', bpSystolic: 'ರಕ್ತದೊತ್ತಡ (mmHg)', riskScore: 'ಅಪಾಯ ಸ್ಕೋರ್',
    enableReminders: 'WhatsApp ಜ್ಞಾಪಕಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ', reminderSaved: 'ಜ್ಞಾಪಕಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ!',
    phone: 'WhatsApp ಸಂಖ್ಯೆ', frequency: 'ಆವರ್ತನ',
    daily: 'ದಿನನಿತ್ಯ', weekly: 'ಸಾಪ್ತಾಹಿಕ', monthly: 'ಮಾಸಿಕ',
    consultFollowup: 'ಮುಂದುವರಿದ ಸಮಾಲೋಚನೆ', medicationAlert: 'ಔಷಧ ಎಚ್ಚರಿಕೆ', bpCheck: 'ರಕ್ತದೊತ್ತಡ ಪರಿಶೀಲನೆ',
    viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ', hide: 'ಮರೆಮಾಡಿ', encryptedPrivate: 'ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮತ್ತು ಖಾಸಗಿ',
    uploadHint: 'ಅಪ್ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ', noDocuments: 'ಯಾವುದೇ ದಾಖಲೆಗಳು ಅಪ್ಲೋಡ್ ಆಗಿಲ್ಲ.',
    diagnosisTitle: 'AI ರೋಗನಿರ್ಣಯ ಸಾರಾಂಶ', diagnosisNote: 'ನಿಮ್ಮ ಮೌಲ್ಯಮಾಪನ ಆಧಾರದ ಮೇಲೆ:',
    possibleCond: 'ಸಂಭವನೀಯ ಸ್ಥಿತಿಗಳು', recommendations: 'ಶಿಫಾರಸುಗಳು', urgency: 'ತುರ್ತು ಮಟ್ಟ',
    emergencySupport: 'ತುರ್ತು ಆಧಾರ', nearbyHospitals: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    detectNearest: 'ಹತ್ತಿರದ್ದು ಪತ್ತೆ ಮಾಡಿ', shareLocation: 'ಸ್ಥಳ ಹಂಚಿಕೊಳ್ಳಿ', shared: 'ಹಂಚಲಾಗಿದೆ',
    whileWaiting: 'ಸಹಾಯಕ್ಕಾಗಿ ಕಾಯುವಾಗ', callAmbulance: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ಕರೆಯಿರಿ',
    bookAppointment: 'ವೈದ್ಯರನ್ನು ಬುಕ್ ಮಾಡಿ', searchPlaceholder: 'ಹೆಸರು ಅಥವಾ ವಿಶೇಷತೆ ಹುಡುಕಿ...',
    ourMission: 'ನಮ್ಮ ಮಿಷನ್', problemsWeSolve: 'ನಾವು ಪರಿಹರಿಸುವ ಸಮಸ್ಯೆಗಳು', ourSolution: 'ನಮ್ಮ ಪರಿಹಾರ',
    teamLead: 'ತಂಡ ಮುಖ್ಯಸ್ಥ',
    heroTagline: 'ಭಾರತದಾದ್ಯಂತ ಸಾವಿರಾರು ರೋಗಿಗಳ ವಿಶ್ವಾಸ',
    heroTitle: 'ಪಿಸಿಒಡಿ, ಸ್ಟ್ರೋಕ್ ಮತ್ತು ಹೃದಯ ಕಾಯಿಲೆಯ ಆರಂಭಿಕ ಪತ್ತೆ',
    heroSub: 'AI ಆರೋಗ್ಯ ವೇದಿಕೆ — ಎಲ್ಲರಿಗೂ ಸ್ಮಾರ್ಟ್ ಆರೋಗ್ಯ ಸೇವೆ.',
    startSymptomCheck: 'ರೋಗಲಕ್ಷಣ ಪರೀಕ್ಷೆ ಪ್ರಾರಂಭಿಸಿ', checkPCODRisk: 'ಪಿಸಿಒಡಿ ಅಪಾಯ ಪರಿಶೀಲಿಸಿ', emergencyHelpNow: 'ತುರ್ತು ಸಹಾಯ',
    usersHelped: 'ಬಳಕೆದಾರರು', support247: 'ಬೆಂಬಲ',
    symptomCheckDesc: 'ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳ ಬಹು-ಹಂತ ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ತಜ್ಞರ ಶಿಫಾರಸುಗಳು.',
    pcodDesc: 'ಪಿಸಿಒಡಿ/ಪಿಸಿಒಎಸ್‌ಗಾಗಿ ವಿಶೇಷ ತಪಾಸಣೆ.',
    neuroCheckDesc: 'ಸ್ಟ್ರೋಕ್‌ನ ಆರಂಭಿಕ ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳನ್ನು ಗುರುತಿಸಿ.',
    womensHealth: 'ಮಹಿಳಾ ಆರೋಗ್ಯ', urgent: 'ತುರ್ತು',
    aiPoweredTools: 'AI-ಚಾಲಿತ ಸಾಧನಗಳು', checkRiskNow: 'ಈಗ ಅಪಾಯ ಪರಿಶೀಲಿಸಿ', startCheck: 'ಪರೀಕ್ಷೆ ಪ್ರಾರಂಭಿಸಿ',
    theProblem: 'ಸಮಸ್ಯೆ', whatWereSolving: 'ನಾವು ಏನು ಪರಿಹರಿಸುತ್ತಿದ್ದೇವೆ',
    howWeHelp: 'ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇವೆ',
    prob1: 'ಪಿಸಿಒಡಿ/ಪಿಸಿಒಎಸ್ ಆರಂಭಿಕ ರೋಗಲಕ್ಷಣಗಳು ಅಡಗಿಕೊಳ್ಳಲ್ಪಡುತ್ತವೆ',
    prob2: 'ಸ್ಟ್ರೋಕ್ ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳು ತಡವಾಗಿ ಪತ್ತೆಯಾಗುತ್ತವೆ',
    prob3: 'ಗ್ರಾಮೀಣ ಸಮುದಾಯಗಳಿಗೆ ತಜ್ಞ ಆರೋಗ್ಯ ಸೇವೆ ಸಿಗುವುದಿಲ್ಲ',
    prob4: 'ಭವಿಷ್ಯವಾಣಿ, ವೈದ್ಯರು ಮತ್ತು ತುರ್ತು ಸೇವೆ ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ ಇಲ್ಲ',
    prob5: 'ವೈದ್ಯಕೀಯ ಭಾಷೆ ಕಡಿಮೆ ಆರೋಗ್ಯ ಸಾಕ್ಷರತೆ ಉಳ್ಳವರನ್ನು ಹೊರಗಿಡುತ್ತದೆ',
    sol1: 'ಸರಳ ಭಾಷೆಯಲ್ಲಿ AI ರೋಗಲಕ್ಷಣ ತಪಾಸಣೆ',
    sol2: 'ಪಿಸಿಒಡಿ/ಪಿಸಿಒಎಸ್ ಅಪಾಯ ಪತ್ತೆ',
    sol3: 'ನ್ಯೂರೋ/ಸ್ಟ್ರೋಕ್ ಎಚ್ಚರಿಕೆ',
    sol4: 'ನಿಮಿಷಗಳಲ್ಲಿ ತಜ್ಞರನ್ನು ಬುಕ್ ಮಾಡಿ',
    sol5: 'ಒಂದೇ ಟ್ಯಾಪ್‌ನಲ್ಲಿ ತುರ್ತು ಸಹಾಯ',
    sol6: 'ಡಿಜಿಟಲ್ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
    ctaTitle: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಅಪಾಯ ಪರಿಶೀಲಿಸಲು ತಯಾರೇ?', ctaSub: '2-3 ನಿಮಿಷ ಮಾತ್ರ. ಉಚಿತ.',
    startFreeCheck: 'ಉಚಿತ ತಪಾಸಣೆ ಪ್ರಾರಂಭಿಸಿ',
    impactSdgs: 'ಪ್ರಭಾವ ಮತ್ತು SDGs', alignedGoals: 'UN ಅಭಿವೃದ್ಧಿ ಗುರಿಗಳೊಂದಿಗೆ ಹೊಂದಾಣಿಕೆ',
    sdg3: 'ಉತ್ತಮ ಆರೋಗ್ಯ ಮತ್ತು ಯೋಗಕ್ಷೇಮ', sdg9: 'ಉದ್ಯಮ, ಆವಿಷ್ಕಾರ ಮತ್ತು ಮೂಲಸೌಕರ್ಯ', sdg10: 'ಅಸಮಾನತೆ ಕಡಿಮೆ',
    learnMore: 'ನಮ್ಮ ಪ್ರಭಾವ ಮತ್ತು ತಂಡದ ಬಗ್ಗೆ ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
  },
};

const LANGUAGES = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'hi', label: 'हि', name: 'हिन्दी' },
  { code: 'ta', label: 'த', name: 'தமிழ்' },
  { code: 'kn', label: 'ಕ', name: 'ಕನ್ನಡ' },
];

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang]?.[key] ?? translations['en'][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}